f2fs: Replace `f2fs_submit_bio()` with `__submit_bio()`
f2fs_submit_bio used to be a function that worked as a wrapper for
__submit_bio(). Since commit [1], f2fs_submit_bio has been removed
in favor of just using __submit_bio(). So, replace f2fs_submit_bio()
with __submit_bio().

This fixes the following compilation error when CONFIG_F2FS_FS_COMPRESSION=y:

ld.lld: error: undefined symbol: f2fs_submit_bio
>>> referenced by compress.c
>>>               f2fs/compress.o:(f2fs_prepare_compress_overwrite) in archive fs/built-in.a

[1]: https://github.com/Atom-X-Devs/android_kernel_xiaomi_scarlet/commit/73a9e103625bcfa16dc61bcad46e0e3692d53232

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>